### ISSUE TITLE
Oh My Posh version 19.17.2

### ISSUE THREAD

**Issue by lucasdepetrisd** [MirkoR89/polarNord#2]
After updating Oh My Posh to version 19.17.2, I noticed that it gave a config error. This issue persists even after reinstalling both Oh My Posh and the Nord theme.

![Imagen de WhatsApp 2024-03-17 a las 02 18 38_e5d16725](https://github.com/MirkoR89/polarNord/assets/66499356/5b29fe22-9443-486e-81be-8ef2813269ed)

This issue is fixed by changing the version number from 2.1 to 2.

```json
{
  "$schema": "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json",
  "version": 2, // Change from 2.1 to 2
  "console_title_template": "{{ .Folder }}",
  "blocks": [
    // The rest of your JSON configuration remains unchanged...
  ]
}
```

Hope this helps someone else. Also, the theme's file could be changed to avoiding future incidents.

**Comment by lucasdepetrisd** [comment]
Opened a PR for this [fix: removed the .1 from the version](https://github.com/MirkoR89/polarNord/pull/3)

**Comment by MirkoR89** [comment]
Thank you Lucas to fixed it
